repos:
- repo: https://github.com/trufflesecurity/trufflehog
  rev: v3.92.4
  hooks:
  - id: trufflehog
    entry: bash -c 'trufflehog git file://. --config=./by-name.yaml --since-commit HEAD --fail'
    stages: ["commit", "push"]
